### PR TITLE
Fix linter to ignore import errors

### PR DESCRIPTION
**Pull request by bobsany16**
@VickiLanger fixing the missing import modules errors that the linter warned.

### CODE REVIEW

**Comment by bobsany16** [comment]
Update: this only resolves the missing import modules but I didn't realize it was so finicky with formatting. Looking for a solution. Don't merge yet

**Comment by bobsany16** [comment]
@VickiLanger sorry I wasn't active as much as I wanted to :(. My apologies. So for this, PR, it will fix the current 'error' of missing module due to the Python linter. It will simply ignore the imports. However, this will then introduce the python Black errors (which it's currently screaming to reformat the files and this is not our goal). You can merge this to bypass the missing import module errors but the python linter bot will still fail because of the format of the files. 

Also, if this is so far not helpful, I could put up a PR to disable the Linter altogether until I or other people can do a better job with the linter. 

What do you think ?

**Review by VickiLanger — APPROVED** [review]
Thanks!

**Comment by VickiLanger** [comment]
> @VickiLanger sorry I wasn't active as much as I wanted to :(. My apologies. So for this, PR, it will fix the current 'error' of missing module due to the Python linter. It will simply ignore the imports. However, this will then introduce the python Black errors (which it's currently screaming to reformat the files and this is not our goal). You can merge this to bypass the missing import module errors but the python linter bot will still fail because of the format of the files.
> 
> Also, if this is so far not helpful, I could put up a PR to disable the Linter altogether until I or other people can do a better job with the linter.
> 
> What do you think ?

No worries. Any help is appreciated and there's no obligation. 

Awesome that it will ignore the imports. I wonder what formating it's complaining about.

**Comment by bobsany16** [comment]
@VickiLanger i think it's the Python Black linter that will want to reformat the .py files. It's very finicky and follows a strict format (like order of imports and then code then comments). I'm trying to do some research on how to configure in the linter bot to ignore the python black configs.

**Pull request merged**
