### PR TITLE
added nouns to tweet_nouns.py

### PR DESCRIPTION
**Pull request by mingweisoo**

### CODE REVIEW

**Comment by mingweisoo** [comment]
Hi does anyone know what's wrong with this commit?

**Review by VickiLanger — APPROVED** [review]
Looks great. Thanks for your contribution. 

---
Make sure to follow [@LGBTQotd on Twitter](https://twitter.com/LGBTQotd) to see the benefits of your work.

**Comment by mingweisoo** [comment]
hi! May I add more?

**Comment by VickiLanger** [comment]
Absolutely. You can add as many as you desire

**Pull request merged**
