### PR TITLE
improving docs

### PR DESCRIPTION
**Pull request by herambchaudhari4121**
HOPE YOU MAY LIKE MY CANGES ON YOU WEBSITE😊😊💖💖😊😊 THAQNKING YOU IN ADVANCE🔥🔥😎🔥🔥

### CODE REVIEW

**Comment by kaif3007** [comment]
.

**Review by VickiLanger — COMMENTED** [review]
How does this improve anything?
Heres' the original:
original

Here's what you suggested:
suggested via pr

**Comment by herambchaudhari4121** [comment]
😼😼😼😼😾😾😾😾😾👿👿👿👿👿💀💀💀👺👺👺💩💩😺😺🤖🤖👾👾👽👽👻👻

**Comment by herambchaudhari4121** [comment]
🙏🙏

**Pull request closed without merging**
