### PR TITLE
Update tweet_historical_events.py

### PR DESCRIPTION
**Pull request by meli94**
The previous code was checking only if event occurred in the exact date of today (2020-10-05), this slices the date and check if there is a month-day match (10-05) and consequently tweets the event. 

There could also be a problem on how the links have been written, I'll look into it and let you know.

### CODE REVIEW

**Review by VickiLanger — APPROVED** [review]
Thanks for your contribution! Though, you're not the only one working this issue. This is new to me. I haven't previously had multiple people trying to work the same issue.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/codqbot) to see the hard work you put in.*

**Comment by bobsany16** [comment]
@meli94 hey, I was looking at the changes and saw that there's a minor error: for line 48 of your changes:

ex: '2020-10-04'
should be `sub = today[5:]` because `today[6:]` would generate '0-04' and not '10-04

**Comment by VickiLanger** [comment]
@meli94 I appreciate your contribution, but @bobsany16 had already opened an issue and been assigned to work on this exact thing. I'm closing this PR without merging it. You're more than welcome to work on other issues.

**Comment by meli94** [comment]
@VickiLanger @bobsany16 I am so sorry about it, I didn't realise it was already been worked on! It is great to learn from you guys :) happy coding!

**Comment by bobsany16** [comment]
@meli94 no worries :) I learned from your code as well. Happy coding

**Pull request closed without merging**
