### PR TITLE
Add various events from New Jersey

### PR DESCRIPTION
**Pull request by Poppamunz**

### CODE REVIEW

**Review by VickiLanger — CHANGES_REQUESTED** [review]
I love these. I had no clue NJ required LGBT history. Please make sure lines 60, 76, and 77 have commas after them.

**Comment by Poppamunz** [comment]
Fixed! I hope I did this right, I'm still pretty new to git.

**Review by VickiLanger — APPROVED** [review]
Fantastic. Thanks for making the changes

**Comment by VickiLanger** [comment]
I understand. Git isn't the easiest thing to learn. Eventually it will make enough sense that you can work with it. Just know, no one has all the stuff memorized. Use a cheat sheet.

**Comment by VickiLanger** [comment]
I will merge this as soon as I get on my computer in the morning

**Pull request merged**
