### PR TITLE
Updated labels

### PR DESCRIPTION
**Pull request by Hinal-Srivastava**
| Hinal Srivastava | Updated Labels | [GitHub](https://github.com/Hinal-Srivastava) | [LinkedIn](https://www.linkedin.com/in/hinal-srivastava-248590156/) |

### CODE REVIEW

**Review by VickiLanger — APPROVED** [review]
Thanks for your contribution! I appreciate the fixes too. When I built the project, for some reason I couldn't think of the word "orientation". 

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/lgbtqotd) to see the hard work you put in.*

**Comment by Hinal-Srivastava** [comment]
> Thanks for your contribution! I appreciate the fixes too. When I built the project, for some reason I couldn't think of the word "orientation".
> 
> _Don't forget to follow the bot on [Twitter](https://www.twitter.com/codqbot) to see the hard work you put in._

You're Welcome!😁👍

**Comment by Hinal-Srivastava** [comment]
@VickiLanger would be really great if you added the `hacktobefest-accepted` label! 🙂

**Comment by VickiLanger** [comment]
I've added it. THough, as long as I merge the PR or approve it, the label isn't necessary.
Screen Shot of hacktoberfest PR requirements PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)

**Pull request merged**
