### PR TITLE
Update tweet.py

### PR DESCRIPTION
**Pull request by Abhishek4uh**
Update in the tweet(py) file.

### CODE REVIEW

**Review by VickiLanger — COMMENTED** [review]
What does `if __name__ == "__main__":` do? I know it's comparing things, but I'm not sure what

**Comment by bobsany16** [comment]
@VickiLanger I think it's away to signal that this file is the main program that's being run by the Python interpreter

**Comment by VickiLanger** [comment]
Thanks, @bobsany16. I should've just looked it up.

> use if` __name__ == “__main__”` block to prevent (certain) code from being run when the module is imported. -[reference](https://medium.com/python-features/understanding-if-name-main-in-python-a37a3d4ab0c3)

**Review by VickiLanger — APPROVED** [review]
Thanks for your contribution.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by Abhishek4uh** [comment]
Thanks for Merge it @VickiLanger

**Pull request merged**
