### PR TITLE
centered text in get_img_for_tweet.py using textwrap

### PR DESCRIPTION
**Pull request by misterdabu**
I tried to maintain the existing calculation details (i.e.: 35 character length / centered for loop checks for <20 char and >286) and focus only on dynamically determining the center and the offset given the image. I've replaced the individual checks for character length per line with the python texwrap function which does some of the heavy lifting. Hope this helps.

### CODE REVIEW

**Review by VickiLanger — COMMENTED** [review]
Wow, there are a lot of files that changed here.  Typically, pull requests should focus on one thing. 

- I haven't used `textwrap` before. Good idea
- What are all the `pycache` files for? Are they necessary?
- What is the purpose for the changes to `tweet.py`?
- Thanks for fixing the spelling in the comments

**Comment by misterdabu** [comment]
Sorry about that. The pycache should have been excluded from push. Forgot to add that to my gitignore. I'll revert the changes to the tweet.py and resubmit. I didn't intend to edit it. I was testing the twitter functionality, but on Windows used dotenv instead of environ[] which had a few changes.

Thanks for checking it.

**Review by VickiLanger — APPROVED** [review]
Fantastic! Thanks for all your work

---
Don't forget to follow the bot on [Twitter](twitter.com/lgbtqotd) to see the hard work you put in.

**Comment by VickiLanger** [comment]
I figured as much that the pycache files weren't necessary, but thought I'd ask because I don't know everything. Thanks for your contribution!

**Pull request merged**
