### PR TITLE
Added a noun to tweet_nowns.py

### PR DESCRIPTION
**Pull request by pradnyavk**
Added a noun to tweet_nowns.py

### CODE REVIEW

**Review by VickiLanger — COMMENTED** [review]
I love this. Please make sure you have a comma at the end of the line.

**Comment by pradnyavk** [comment]
Sure thing!

**Review by pradnyavk — COMMENTED** [review]
done!

**Review by VickiLanger — APPROVED** [review]
Fantastic! Thank you.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Pull request merged**
