### PR TITLE
Added new adjectives

### PR DESCRIPTION
**Pull request by Praveenk8051**
Added new Adjectives as my PR practice

### CODE REVIEW

**Comment by Praveenk8051** [comment]
@VickiLanger I would be interested in knowing why this CI/CD failed!

**Review by VickiLanger — CHANGES_REQUESTED** [review]
Love the adjectives. Though, I'm not sure what the `.idea` stuff is. Would it be possible to remove those?

**Comment by VickiLanger** [comment]
> @VickiLanger I would be interested in knowing why this CI/CD failed!

This isn't anything on you. The ci/cd checks are broken 😞

**Comment by Praveenk8051** [comment]
Removed `.idea` folder

**Review by Praveenk8051 — COMMENTED** [review]
CI/CD failed again. 
As per the error in this [page](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports), the error is due to missing package `PIL`

I would be interested in knowing how you solved it. @VickiLanger 

Screenshot 2021-03-20 at 20 23 54

**Review by VickiLanger — APPROVED** [review]
Thanks for your work. To see all your work in action make sure to follow [@LGBTQotd](https://twitter.com/LGBTQotd) on twitter

**Pull request merged**
