### PR TITLE
i make this game using flappy bird

### PR DESCRIPTION
**Pull request by KartikJangir**

### CODE REVIEW

**Comment by JasirZaeem** [comment]
This repo is not the place for this game.

**Comment by am1983** [comment]
There are some issues that would need to be addressed with this PR beyond the question of whether it belongs here.

1) The file you added is not a proper Python file although, by my best reckoning, it's valid Python.
2) None of the required assets (gallery/sprites/...) were actually included.

I'd definitely be curious to know more about the intent here.

**Comment by JasirZaeem** [comment]
I assume this PR was made to reach 4 PRs for hacktoberfest. The other PRs they've made confirm that.
The code is not original and is copied verbatim from https://codewithharry.com/videos/python-tutorials-for-absolute-beginners-122 They just made a new file on GitHub's web editor and pasted that code, hence it is neither a valid python file nor it has any accompanying assets.

**Comment by am1983** [comment]
The more I look at the situation, the more I agree with you. Hacktoberfest was a good idea... until it wasn't. Thanks for your input on this!

**Pull request closed without merging**
