### PR TITLE
Update tweet_historical_events.py

### PR DESCRIPTION
**Pull request by NoSoyTuMadre**
Fixed some grammatical errors

### CODE REVIEW

**Review by NoSoyTuMadre — COMMENTED** [review]
I commented out line 555 due to pylinter error when merging in tweet_nouns.py (which I didn't change initially). I corrected grammatical error in tweet_historical_events.py.

**Review by NoSoyTuMadre — COMMENTED** [review]
Updated tweet_historical_events.py

**Review by VickiLanger — APPROVED** [review]
Thanks for your contribution

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Review by VickiLanger — APPROVED** [review]
Thanks for your contribution

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Pull request merged**
