### PR TITLE
Attempt at solving issue #203 - random font selection

### PR DESCRIPTION
**Pull request by tejusrevi**
I tried to solve this issue by creating a list of all files in assets folder and choosing a random item from that list for font_type and font_type2.

But few fonts gave a distorted output
post_98

### CODE REVIEW

**Review by VickiLanger — APPROVED** [review]
This definitely looks like it should work. I figured some of the fonts aren't gonna work well. I might have to remove the ones that don't work or open an issue to figure out formatting each font

Thanks so much for contributing.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by VickiLanger** [comment]
@tejusrevi If you don't mind me asking, how did you test this locally? That's something I haven't done much

**Comment by tejusrevi** [comment]
@VickiLanger I called the function in the main body of get_img_for_tweet.py and ran just that .py file.

**Comment by VickiLanger** [comment]
> @VickiLanger I called the function in the main body of get_img_for_tweet.py and ran just that .py file.

Hmm, okay. I think, something like below?

```
>>> from get_img_for_tweet.py import *
>>> get_img_for_tweet("some strings of things to test the image")
```

**Comment by tejusrevi** [comment]
Yeah. That's exactly what I did. Only difference is that I didn't import into an other python file.

**Comment by VickiLanger** [comment]
Thanks for helping. I appreciate it

**Pull request merged**
