### PR TITLE
Add more adjectives

### PR DESCRIPTION
**Pull request by Alkahwaji**
Add more common adjectives in B letter.

### CODE REVIEW

**Review by VickiLanger — APPROVED** [review]
I look forward to seeing what awful sentence has cockroach in it. Thanks for your contribution. 

---
Make sure to follow [@LGBTQotd on Twitter](https://twitter.com/LGBTQotd) to see the benefits of your work.

**Comment by Alkahwaji** [comment]
Thank you. I tried a lot of pull requests and contributions but not all of them accepted and I don't know why. Can you help me?

**Comment by VickiLanger** [comment]
@Alkahwaji I accepted all of your commits in this PR. Are you talking about other repos?

**Comment by Alkahwaji** [comment]
yes. they gave me ! mark. That means it has not been accepted. Why?

**Comment by VickiLanger** [comment]
That is weird. I'm not sure why they would do that. Have you asked the maintainers of those repos?

**Pull request merged**
