### PR TITLE
Added some historical events related to Spain #5 and #54

### PR DESCRIPTION
**Pull request by dylan-nogueras**

### CODE REVIEW

**Comment by dylan-nogueras** [comment]
I'm not sure why it has failed. Let me know if I have to fix something. Thanks! :)

**Comment by VickiLanger** [comment]
No worries on the checks. That's on me. It's supposed to greet first-time contributors, but it seems to be failing.

**Review by VickiLanger — APPROVED** [review]
I love these. Thank you so much for contributing.

---
*Don't forget to follow the bot on [Twitter](https://www.twitter.com/LGBTQotd) to see the hard work you put in.*

**Comment by dylan-nogueras** [comment]
Thank you for letting me contribute! I love the idea of this project.

**Pull request merged**
